name: Telepartacyja
version: '${version}'
main: by.siarhiejbahdaniec.telepartacyja.Telepartacyja
api-version: '1.20'
depend: [kotlin-stdlib]

commands:
  spawn:
    usage: /spawn
    description: тэлепартуе гульца на заданыя каардынаты

permissions:
  spawn.bypass:
    delay:
      description: Адмяняе затрымку перад тэлепартаваннем, гулец які мае пермішан тэлепартуецца адразу пасля выканання каманды.

    cancel-on-move:
      description: Адмяняе скасаванне тэлепорту калі гулец рухаецца.

    cooldown:
      description: Адмяняе затрымку да паўторнага карыстання камандай /spawn
