messages:
  # successful teleport to spawn
  teleport: '&aВы на спаўне.'
  # if the player still has an active teleport cooldown
  cooldown-left: '&cКалі ласка, пачакайце &4%s &cсекунд(ы) перад тым як паўтарыць.'
  #
  # time left until the player gets teleported to spawn
  delay-left: '&6Вы будзеце тэлепартаваны праз &e%s &6секунд.'
  # delayed teleport failed because the player moved
  teleport-cancelled: '&cТэлепорт скасаваны. Не рухайцеся!'
  # teleport event was cancelled
  teleport-cancelled-unknown: '&cТэлепорт чамусьці быў скасаваны ¯\_(ツ)_/¯'
  #
  # spawn set at current position
  spawn-set: '&aКропка спаўна абрана'
  # first spawn set at current position
  first-spawn-set: '&aКропка спаўна для новых гульцоў абрана'
  #
  # config reloaded
  config-reload: '&aКанфіг перазагружаны'
  #
  # no spawn set in config - set one with /spawn set
  no-spawn: '&cНяма абранай кропкі спаўна!'
  # command cannot be used in console
  no-player: '&cКаманду можна выкарыстоўваць толькі як гулец!'

spawn:
  ==: org.bukkit.Location
  world: world
  x: -19.5
  y: 68.0
  z: -301.5
  yaw: 176.0
  pitch: 7.0

first-spawn:
  ==: org.bukkit.Location
  world: world
  x: -19.5
  y: 68.0
  z: -301.5
  yaw: 176.0
  pitch: 7.0

teleport:
  delay: 3
  cooldown: 10

server:
  tps: 20